#pragma once

#include "../Core/Inc/Application.h"
#include "../Core/Inc/Object.h"
#include "../Core/Inc/Runtime.h"
#include "../Core/Inc/Containers/Array.h"
#include "../Core/Inc/Math/Math.h"
#include "../Core/Inc/String/String.h"
#include "../Core/Inc/String/NameTable.h"
#include "../Core/Inc/String/Name.h"
#include "../Core/Inc/Time/Time.h"
#include "../Core/Inc/Time/PlatformTime.h"
#include "../Core/Inc/Utility/Hash.h"
#include "../Core/Inc/Utility/Log.h"
#include "../Core/Inc/Utility/Memory.h"